name: Test For Pull Request 

on: [pull_request]

jobs:
  unit_test:

    runs-on: windows-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2
  
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1
      
    - name: Restore
      run: MSBuild -t:restore -property:Configuration=Release
        
    - name: Build
      run: MSBuild -property:Configuration=Release
        
    - name: Test
      run: VSTest.Console DotnetSpiderTests\bin\Release\*\DotnetSpiderTests.dll
