name: Test For Pull Request 

on: [pull_request]

jobs:
  unit_test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build with dotnet
      run: |
        dotnet restore --configuration Release
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.exe" ./DotnetSpider3-Remake.sln /Build Release
        
    - name: Test with dotnet
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"  DotnetSpiderTests/bin/Release/net45/DotnetSpiderTests.dll
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"  DotnetSpiderTests/bin/Release/netcoreapp3.1/DotnetSpiderTests.dll
